FILE=cpu

MODULES_SYNTH = ../csr/csr.sv ../alu/alu.sv ../control/control.sv ../imm_gen/imm_gen.sv ../pc_unit/pc_unit.sv ../regs/regs.sv memory.sv spi_master.sv i2c_master.sv uart_tx.v
MODULES_SIM = $(MODULES_SYNTH) sram_sim.sv

include ../Makefile.inc
