FILE=plru_m
#FILE=cache_direct_mapped
TARGET=synth_ice40
#MODULES_SIM = ../imm_gen/imm_gen.sv# ../constants.sv
#MODULES_SYNTH = $(MODULES_SIM)
MODULES_SYNTH = ./one_mod.sv
MODULES_SIM = $(MODULES_SYNTH)

include ../../../Makefile.inc
