FILE=control
TARGET=synth_ice40
#MODULES_SIM = ../imm_gen/imm_gen.sv# ../constants.sv
#MODULES_SYNTH = $(MODULES_SIM)
MODULES_SYNTH = ../imm_gen/imm_gen.sv  ../constants.sv
MODULES_SIM = ../imm_gen/imm_gen.sv 

include ../Makefile.inc
