FILE=cache_module
#FILE=cache_direct_mapped
TARGET=synth_ice40

MODULES_SYNTH = ../../../yosys_spram/spram.sv ../../../yosys_spram/sbram.sv
MODULES_SIM = $(MODULES_SYNTH)

include ../../../Makefile.inc
