FILE=id_cache_direct_mapped_large_misaligned
#FILE=cache_direct_mapped
TARGET=synth_ice40
#MODULES_SIM = ../imm_gen/imm_gen.sv# ../constants.sv
#MODULES_SYNTH = $(MODULES_SIM)
MODULES_SYNTH = ../../../constants.sv ../../../cpu/spi_master.sv
MODULES_SIM = ../../../constants.sv ../../../cpu/sram_sim.sv ../../../cpu/spi_master.sv

include ../../Makefile.inc
