FILE=cache_way
#FILE=cache_direct_mapped
TARGET=synth_ice40
#MODULES_SIM = ../imm_gen/imm_gen.sv# ../constants.sv
#MODULES_SYNTH = $(MODULES_SIM)
MODULES_SYNTH =
MODULES_SIM =

include ../../../Makefile.inc
